"""
price_check.py
Checks pricing pages for all 7 reviewed tools.
Compares against known prices stored in the script.
Flags discrepancies by writing price-report.txt and exiting with code 1.
GitHub Actions uses the exit code to decide whether to open an Issue.
"""

import requests
import sys
import os
from datetime import datetime

# ── KNOWN PRICES (update these when you update the site) ──────────────────────
KNOWN_PRICES = {
    "Jasper AI":          {"price_str": "39", "check_url": "https://www.jasper.ai/pricing"},
    "Notion AI":          {"price_str": "10",  "check_url": "https://www.notion.so/pricing"},
    "Canva Magic Suite":  {"price_str": "15",  "check_url": "https://www.canva.com/pricing/"},
    "Semrush":            {"price_str": "139", "check_url": "https://www.semrush.com/prices/"},
    "Tidio":              {"price_str": "29",  "check_url": "https://www.tidio.com/pricing/"},
    "Zapier":             {"price_str": "20",  "check_url": "https://zapier.com/pricing"},
    "Kit (ConvertKit)":   {"price_str": "25",  "check_url": "https://kit.com/pricing"},
}

HEADERS = {
    "User-Agent": "Mozilla/5.0 (compatible; PriceBot/1.0; price accuracy check)"
}

def check_tool(name, info):
    """Returns (ok: bool, message: str)"""
    try:
        resp = requests.get(info["check_url"], headers=HEADERS, timeout=15, allow_redirects=True)
        page_text = resp.text.lower()
        known = info["price_str"]

        # Simple heuristic: does the known price appear on the page?
        if f"${known}" in page_text or f"${known}/" in page_text or f"${known} " in page_text:
            return True, f"✓ {name}: ${known} confirmed on pricing page"
        else:
            return False, f"⚠️  {name}: ${known}/mo NOT found on pricing page — manual check needed\n   URL: {info['check_url']}"
    except requests.RequestException as e:
        return None, f"⚡ {name}: Could not reach pricing page ({e})\n   URL: {info['check_url']}"


def main():
    print(f"Price check — {datetime.utcnow().strftime('%Y-%m-%d')}")
    print("=" * 60)

    results = []
    has_alert = False

    for name, info in KNOWN_PRICES.items():
        ok, msg = check_tool(name, info)
        print(msg)
        results.append(msg)
        if ok is False:
            has_alert = True

    report_lines = [
        f"# Price Monitor Report — {datetime.utcnow().strftime('%Y-%m-%d')}",
        "",
        "The monthly automated price check flagged the following:",
        ""
    ] + results + [
        "",
        "## Action Required",
        "1. Visit each flagged pricing page",
        "2. Update the price in `index.html` if changed",
        "3. Update the `KNOWN_PRICES` dict in `scripts/price_check.py`",
        "4. Commit and push — GitHub Actions will deploy the update automatically",
        "",
        f"*Generated by price_check.py on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*"
    ]

    with open("price-report.txt", "w") as f:
        f.write("\n".join(report_lines))

    if has_alert:
        print("\n⚠️  Alerts found — GitHub Issue will be created.")
        sys.exit(1)
    else:
        print("\n✓ All prices look current. No action needed.")
        sys.exit(0)


if __name__ == "__main__":
    main()
